name: Docker Image CI

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main']
  
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Login Dockerhub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build the Docker image
          run: docker build -t gaeboptoday-server .
        - name: taging
          run: docker tag gaeboptoday-server:latest siyoun/gaeboptoday-server:latest
        - name: Push to Dockerhub
          run: docker push siyoun/gaeboptoday-server:latest